# Configurando a conexão com MongoDB
spring.data.mongodb.uri=mongodb+srv://gabrielfernandeza8_db_user:hbUCpbNRdCHd1qCD@cluster0.eonl9dq.mongodb.net/pizzaria?retryWrites=true&w=majority&ssl=true&sslInvalidHostNameAllowed=true
spring.data.mongodb.database=pizzaria

# Autenticação padrão do Spring Security
spring.security.user.name=user
spring.security.user.password=shalom

# Configurações do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

logging.level.com.atrah=DEBUG